In [1]:
import array as arr 

a = arr.array("i",[21,16])

print(a)

array('i', [21, 16])


In [2]:
copyArray = arr.array(a.typecode,[x for x in a])

In [6]:
print(copyArray)
for i in copyArray:
    print(i, end =" ")

array('i', [21, 16])
21 16 

In [14]:
import numpy as np 

b = np.linspace(16,21,2)

In [15]:
b

array([16., 21.])

In [18]:
c = np.arange(10,20,2)

In [19]:
c

array([10, 12, 14, 16, 18])

In [22]:
d = np.full(4,5)

In [23]:
d

array([5, 5, 5, 5])